apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  
spec:
 # storageClassName: generic
  accessModes:
  - ReadWriteMany      
  resources:
     limits:
       storage: 5Gi
     requests:
       storage: 5Gi 
 # The selector field defines all labels necessary in a PV in order to match this claim
  selector: 
    matchLabels:
      storage-type: nfs