apiVersion: v1
kind: ServiceAccount
metadata:
  name: hz-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: hz-client
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metric-tester
  labels:
    app: prometheus-metric-tester
spec:
  selector:
    matchLabels:
      app: prometheus-metric-tester
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-metric-tester
    spec:
      serviceAccountName: hz-client
      containers:
      - name: prometheus-metric-tester
        image: sunnyvale/prometheus-metric-tester
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/hazelcast.yaml
          subPath: hazelcast.yaml
          readOnly: true
          name: test-app-cm
        ports:
        - containerPort: 8102
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /metric-test/actuator/prometheus
            port: 8102
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: test-app-cm
        configMap:
          name: test-app-cm 
          items:
            - key: hazelcast.yaml
              path: hazelcast.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metric-tester-service
  labels:
    app: prometheus-metric-tester-service
spec:
  ports:
    - port: 8102
      name: http
      targetPort: 8102
  selector:
    app: prometheus-metric-tester
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metric-tester-hazelcast-service
  labels:
    app: prometheus-metric-tester-hazelcast-service
spec:
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
  selector:
    app: prometheus-metric-tester
