apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: default
spec:
  rules:
  - host: 192-168-26-11.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: http
      - path: /whoami
        backend:
          serviceName: whoami-service
          servicePort: http