apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-dynamic
  #annotations: 
  #  storageclass.kubernetes.io/is-default-class: true
provisioner: example.com/nfs
reclaimPolicy: Delete
parameters:
  mountOptions: "vers=4.1"
