apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: full
  namespace: velero
spec:
  schedule: "* * * * *"
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: true
    includedNamespaces:
    - 'velero-test'
    includedResources: null
    labelSelector: null
    storageLocation: minio-bsl
    ttl: 720h0m0s
    volumeSnapshotLocations:
    - minio-vsl
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: manifests
  namespace: velero
spec:
  schedule: "* * * * *"
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: true
    snapshotVolumes: false
    includedNamespaces:
    - 'velero-test'
    includedResources: null
    labelSelector: null
    storageLocation: minio-bsl
    ttl: 720h0m0s
    volumeSnapshotLocations:
    - minio-vsl